modLoader = "javafml"
loaderVersion = "*"
license = "LGPLv3"
issueTrackerURL="https://JavaJumper/TempLate/issues"

[[mods]]
modId = "template"
version = "${version}"
displayName = "${name}"
authors = "JavaJumper"
description = ""
logoFile = "assets/template/icon.png"
logoBlur = false

[[mixins]]
config = "template-common.mixins.json"

[[mixins]]
config = "template-neoforge.mixins.json"